version: '3.4'

services:

  identityserverdb:
   image: mcr.microsoft.com/mssql/server:2017-latest

  rabbitmq:
   image: rabbitmq:3-management-alpine

  middlewares.api:
    image: ${DOCKER_REGISTRY-}middlewaresapi
    build:
      context: .
      dockerfile: Services/Middlewares/Middlewares.API/Dockerfile

  identityserver:
    image: ${DOCKER_REGISTRY-}identityserver
    build:
      context: .
      dockerfile: IdentityServer/IdentityServer/Dockerfile


  ocelotapigw:
    image: ${DOCKER_REGISTRY-}ocelotapigw
    build:
      context: .
      dockerfile: APIGateways/OcelotAPIGW/Dockerfile

